#!/usr/bin/env node
/**
 * End-to-end auto-updater simulation.
 *
 * Drives the REAL `electron/updater.ts` through a full check -> download ->
 * update-downloaded cycle against a fake update feed served from a local
 * HTTP server, so the updater can be exercised without cutting a GitHub
 * release or shipping a signed build.
 *
 * Usage:
 *   npm run test:updater-sim
 *   npm run test:updater-sim -- --keep-logs
 *
 * Exits non-zero on failure, so it is CI-usable.
 *
 * Ports: binds to an ephemeral port chosen by the OS. It never touches 4001
 * (backend) or 5173 (vite dev server).
 */

import { createServer } from 'http';
import { createHash } from 'crypto';
import { spawn } from 'child_process';
import { mkdtempSync, writeFileSync, rmSync } from 'fs';
import { tmpdir } from 'os';
import { join, resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, '..');

const keepLogs = process.argv.includes('--keep-logs');

/** The version the fake feed advertises. Far above anything real. */
const FAKE_VERSION = '99.0.0';

const platform = process.platform;

// macOS is intentionally not simulated: MAC_UPDATES_ENABLED is false until the
// app is signed (issue #10), so there is no shipped code path to exercise, and
// MacUpdater's Squirrel handoff needs a signature we do not have.
if (platform === 'darwin') {
    console.log('⏭️  Skipping updater sim on macOS — in-app updates are disabled there until code signing lands (issue #10).');
    process.exit(0);
}

const ARTIFACT_NAME = platform === 'win32'
    ? `Claudia-Setup-${FAKE_VERSION}.exe`
    : `Claudia-${FAKE_VERSION}.AppImage`;

const METADATA_NAME = platform === 'win32' ? 'latest.yml' : 'latest-linux.yml';

// ---------------------------------------------------------------------------
// Fake feed
// ---------------------------------------------------------------------------

/**
 * A dummy artifact. Never executed — the sim stops at `update-downloaded` and
 * never calls quitAndInstall — but it must hash correctly, because verifying
 * the sha512 from the metadata is exactly what we want to prove works.
 */
const artifact = Buffer.from(
    `This is not a real Claudia installer. Generated by scripts/updater-sim.mjs at ${new Date().toISOString()}.\n`.repeat(64),
    'utf-8'
);
const sha512 = createHash('sha512').update(artifact).digest('base64');

const metadata = [
    `version: ${FAKE_VERSION}`,
    'files:',
    `  - url: ${ARTIFACT_NAME}`,
    `    sha512: ${sha512}`,
    `    size: ${artifact.length}`,
    `path: ${ARTIFACT_NAME}`,
    `sha512: ${sha512}`,
    `releaseDate: '${new Date().toISOString()}'`,
    ''
].join('\n');

const requestLog = [];

const server = createServer((req, res) => {
    const url = (req.url || '').split('?')[0];
    requestLog.push(url);
    console.log(`   [feed] ${req.method} ${url}`);

    if (url === `/${METADATA_NAME}`) {
        res.writeHead(200, { 'Content-Type': 'text/yaml', 'Content-Length': Buffer.byteLength(metadata) });
        res.end(metadata);
        return;
    }
    if (url === `/${ARTIFACT_NAME}`) {
        res.writeHead(200, { 'Content-Type': 'application/octet-stream', 'Content-Length': artifact.length });
        res.end(artifact);
        return;
    }
    // .blockmap absence is expected and non-fatal: electron-updater falls back
    // to a full download when differential data is missing.
    res.writeHead(404, { 'Content-Type': 'text/plain' });
    res.end('not found');
});

function fail(message, extra) {
    console.error(`\n❌ ${message}`);
    if (extra) console.error(extra);
    try { server.close(); } catch { /* already closing */ }
    process.exit(1);
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------

const userDataDir = mkdtempSync(join(tmpdir(), 'claudia-updater-sim-'));

server.listen(0, '127.0.0.1', () => {
    const { port } = server.address();
    const feedUrl = `http://127.0.0.1:${port}`;

    if (port === 4001 || port === 5173) {
        fail(`Refusing to run: the OS handed us reserved port ${port}.`);
        return;
    }

    console.log('\n🔄 Claudia updater simulation');
    console.log(`   platform:   ${platform}`);
    console.log(`   feed:       ${feedUrl}`);
    console.log(`   advertises: ${FAKE_VERSION} (${ARTIFACT_NAME}, ${artifact.length} bytes)`);
    console.log(`   userData:   ${userDataDir}\n`);

    // In an unpackaged build electron-updater reads its provider config from
    // disk during the download step, so give it one pointing at our feed.
    const devConfigPath = join(userDataDir, 'dev-app-update.yml');
    writeFileSync(devConfigPath, `provider: generic\nurl: ${feedUrl}\n`, 'utf-8');

    const electronBin = process.platform === 'win32'
        ? join(rootDir, 'node_modules', 'electron', 'dist', 'electron.exe')
        : join(rootDir, 'node_modules', '.bin', 'electron');

    const child = spawn(electronBin, [join(__dirname, 'updater-sim-main.mjs'), '--user-data-dir', userDataDir], {
        cwd: rootDir,
        env: {
            ...process.env,
            CLAUDIA_UPDATER_SIM_FEED: feedUrl,
            CLAUDIA_UPDATER_SIM_EXPECT: FAKE_VERSION,
            CLAUDIA_UPDATER_SIM_USERDATA: userDataDir,
            CLAUDIA_UPDATER_SIM_CONFIG: devConfigPath,
            ELECTRON_ENABLE_LOGGING: '1'
        },
        stdio: ['ignore', 'pipe', 'pipe']
    });

    let stdout = '';
    let stderr = '';
    child.stdout.on('data', d => { const s = String(d); stdout += s; process.stdout.write(s); });
    child.stderr.on('data', d => { const s = String(d); stderr += s; process.stderr.write(s); });

    const timeout = setTimeout(() => {
        console.error('\n❌ Timed out after 120s');
        child.kill();
    }, 120_000);

    child.on('exit', code => {
        clearTimeout(timeout);
        server.close();
        if (!keepLogs) {
            try { rmSync(userDataDir, { recursive: true, force: true }); } catch { /* best effort */ }
        }

        const sawMetadata = requestLog.some(u => u === `/${METADATA_NAME}`);
        const sawArtifact = requestLog.some(u => u === `/${ARTIFACT_NAME}`);

        console.log('\n── feed requests ──');
        console.log(requestLog.length ? requestLog.map(u => `   ${u}`).join('\n') : '   (none)');

        if (code !== 0) {
            fail(`Electron sim exited with code ${code}`, stderr.slice(-2000));
            return;
        }
        if (!sawMetadata) {
            fail(`The updater never fetched ${METADATA_NAME} — the check did not reach the feed.`);
            return;
        }
        if (!sawArtifact) {
            fail(`The updater never fetched ${ARTIFACT_NAME} — the download did not happen.`);
            return;
        }
        if (!stdout.includes('SIM_RESULT_OK')) {
            fail('Sim did not report success.', stdout.slice(-2000));
            return;
        }

        // Acceptance criterion: switching updates off (and pinning a version)
        // must produce ZERO feed traffic, not merely skip the install. The
        // child pings /__checkpoint_disabled immediately before flipping the
        // switch, so anything logged after it is a violation.
        const checkpoint = requestLog.indexOf('/__checkpoint_disabled');
        if (checkpoint === -1) {
            fail('Sim never reached the disabled-updates checkpoint.');
            return;
        }
        const afterDisable = requestLog.slice(checkpoint + 1);
        if (afterDisable.length > 0) {
            fail(
                'Disabled/pinned updater still contacted the feed — "off" must mean zero network calls.',
                `Unexpected requests: ${afterDisable.join(', ')}`
            );
            return;
        }

        console.log('\n✅ Updater simulation passed');
        console.log('   check → update-available → download → update-downloaded, sha512 verified.');
        console.log('   notify behaviour did not auto-download.');
        console.log('   disabled + pinned made zero feed requests.');
        if (keepLogs) console.log(`   userData kept at ${userDataDir}`);
        process.exit(0);
    });

    child.on('error', err => {
        clearTimeout(timeout);
        server.close();
        fail(`Could not launch Electron at ${electronBin}`, String(err));
    });
});
